# Generated by Django 4.2.30 on 2026-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycosting',
            name='complimentary_bfast',
            field=models.IntegerField(default=0, verbose_name='Complimentary Breakfast'),
        ),
    ]
